version: '3.8'

services:

# 1. PostgreSQL Database Service (Official Image)

  db:
    image: postgres:16-alpine 
    container_name: salesync_postgres_db
    restart: always
    environment:
      POSTGRES_USER: changeME
      POSTGRES_PASSWORD: changeME
      POSTGRES_DB: changeME
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      

# 2. Spring Boot Backend Service (salesync API)

  backend:
    container_name: salesync_backend
    build: 
      context: .
      dockerfile: infra/spring-boot/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/changeME
      SPRING_DATASOURCE_USERNAME: changeME
      SPRING_DATASOURCE_PASSWORD: changeME
    depends_on:
      db:
        condition: service_healthy


# 3. Next.js Frontend Service (salesync Client)

  frontend:
    container_name: salesync_frontend
    build:
      context: .
      dockerfile: infra/next-js/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    depends_on:
      backend:
        condition: service_started

volumes:
  postgres_data: